# SPDX-License-Identifier: BSD-3-Clause */

# Copyright (c) 2023 Rockchip Electronics Co., Ltd.

PROJECT := RK2118
SOC := RK2118
CPU := -mcpu=cortex-m33 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=hard
LINKER_SCRIPT := gcc_arm.ld

include ../../common/GCC/Cortex-M.mk
